# Generated by Django 4.0.3 on 2022-03-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('name', models.CharField(max_length=500)),
                ('id', models.IntegerField(max_length=500, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=500)),
            ],
        ),
    ]
