# Generated by Django 4.0.3 on 2022-03-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('number', models.IntegerField(max_length=11)),
            ],
        ),
    ]
