# Generated by Django 3.1.1 on 2022-03-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
