# Generated by Django 3.1.1 on 2022-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filtring',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rollNum', models.IntegerField()),
                ('passedby', models.CharField(max_length=50)),
            ],
        ),
    ]
