# Generated by Django 4.0.3 on 2022-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rollNum', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
